/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.hibernateautogenerated1an;

/**
 *
 * @author manuelmsni
 */
public class HibernateAutoGenerated1aN {

    public static void main(String[] args) {
        
        
        
    }
}
