/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testhibernate20.view;

import com.mycompany.testhibernate20.model.GenreTableModel;
import com.mycompany.testhibernate20.model.PersonTableModel;

/**
 *
 * @author Vespertino
 */
public class MainView extends javax.swing.JFrame {

    private PersonTableModel personTableModel;
    private GenreTableModel genreTableModel;
    /**
     * Creates new form PersonList
     */
    public MainView() {
        personTableModel = new PersonTableModel();
        genreTableModel = new GenreTableModel();
        initComponents();
        personJTable.setModel(personTableModel);
        genreJTable.setModel(genreTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        personTabPanel = new javax.swing.JPanel();
        personJScrollPanel = new javax.swing.JScrollPane();
        personJTable = new javax.swing.JTable();
        personButtonsPanel = new javax.swing.JPanel();
        addPersonButton = new javax.swing.JButton();
        genreTabPanel = new javax.swing.JPanel();
        genreJScrollPanel = new javax.swing.JScrollPane();
        genreJTable = new javax.swing.JTable();
        genreButtonsPanel = new javax.swing.JPanel();
        addGenreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personTabPanel.setLayout(new java.awt.BorderLayout());

        personJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        personJScrollPanel.setViewportView(personJTable);

        personTabPanel.add(personJScrollPanel, java.awt.BorderLayout.CENTER);

        personButtonsPanel.setPreferredSize(new java.awt.Dimension(437, 40));
        personButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addPersonButton.setText("Add Person");
        addPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonButtonActionPerformed(evt);
            }
        });
        personButtonsPanel.add(addPersonButton);

        personTabPanel.add(personButtonsPanel, java.awt.BorderLayout.SOUTH);

        jTabbedPane2.addTab("Persons", personTabPanel);

        genreTabPanel.setLayout(new java.awt.BorderLayout());

        genreJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        genreJScrollPanel.setViewportView(genreJTable);

        genreTabPanel.add(genreJScrollPanel, java.awt.BorderLayout.CENTER);

        genreButtonsPanel.setPreferredSize(new java.awt.Dimension(0, 40));
        genreButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addGenreButton.setText("Add Genre");
        genreButtonsPanel.add(addGenreButton);

        genreTabPanel.add(genreButtonsPanel, java.awt.BorderLayout.SOUTH);

        jTabbedPane2.addTab("Genres", genreTabPanel);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonButtonActionPerformed
        (new PersonDetails()).setVisible(true);
    }//GEN-LAST:event_addPersonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGenreButton;
    private javax.swing.JButton addPersonButton;
    private javax.swing.JPanel genreButtonsPanel;
    private javax.swing.JScrollPane genreJScrollPanel;
    private javax.swing.JTable genreJTable;
    private javax.swing.JPanel genreTabPanel;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel personButtonsPanel;
    private javax.swing.JScrollPane personJScrollPanel;
    private javax.swing.JTable personJTable;
    private javax.swing.JPanel personTabPanel;
    // End of variables declaration//GEN-END:variables
}
