/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.multihilos;

import java.awt.Color;
import static java.lang.Thread.sleep;

/**
 *
 * @author manuelmsni
 */
public class Ej7 extends javax.swing.JFrame {

    Chronos cronometro;
    /**
     * Creates new form Ej7
     */
    public Ej7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        pauseButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 33));
        getContentPane().setLayout(new java.awt.FlowLayout());

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        getContentPane().add(outputLabel);

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pauseButton);

        resumeButton.setText("Resume");
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resumeButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        cronometro.pausar();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        cronometro.reanudar();
    }//GEN-LAST:event_resumeButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startButton.setVisible(false);
        cronometro = new Chronos(60);
        cronometro.start();
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej7().setVisible(true);
            }
        });
    }
    
    public class Chronos extends Thread {
        private Object lock;
        private long sec;
        private boolean paused;

        public Chronos(long sec) {
            this.sec = sec;
            this.lock = new Object();
            this.paused = false;
        }

        public void pausar() {
            synchronized (lock) {
                paused = true;
            }
        }

        public void reanudar() {
            synchronized (lock) {
                paused = false;
                lock.notify();
            }
        }

        public void run() {
            while (sec >= 0) {
                try {
                    synchronized (lock) {
                        while (paused) {
                            lock.wait();
                        }
                    }

                    sleep(1000);
                    outputLabel.setText(getFormatClock());
                } catch (InterruptedException ex) {
                    System.out.println("Chronos was interrupted!");
                }
                sec--;
            }
            outputLabel.setForeground(Color.RED);
        }

        public String getFormatClock() {
            return formatearTiempo(sec);
        }

        public static String formatearTiempo(long segundosTotales) {
            long dias = segundosTotales / (24 * 3600);
            long horas = (segundosTotales % (24 * 3600)) / 3600;
            long minutos = ((segundosTotales % (24 * 3600)) % 3600) / 60;
            long segundos = ((segundosTotales % (24 * 3600)) % 3600) % 60;

            return String.format("%dd %dh %dm %ds", dias, horas, minutos, segundos);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton resumeButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
