/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.hibernateautogenerated;

import com.mycompany.hibernateautogenerated.controller.MainController;
import com.mycompany.hibernateautogenerated.model.Book;
import com.mycompany.hibernateautogenerated.model.Person;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author manuelmsni
 */
public class HibernateAutoGenerated {

    
    
    public static void main(String[] args) {
        //datosDePrueba();
        iniciaVista();
    }
    
    private static void iniciaVista(){
        Vista v = new Vista();
        v.bucleDePrograma();
        try {
            v.close();
        } catch (IOException ex) {
            Logger.getLogger(HibernateAutoGenerated.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private static void datosDePrueba(){
        Book b = new Book("El señor de los anillos");
        Book b2 = new Book("Pepa la cerda");
        Person p = new Person("Tolkien");
        Person p2 = new Person("Cervantes");
        
        b.addPerson(p);
        b.addPerson(p2);
        p.addBook(b);
        p2.addBook(b);
        
        b2.addPerson(p2);
        p2.addBook(b2);
        
        
        try{
            MainController.addBook(b);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
