version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        command: bash -c "php -S 0.0.0.0:8080 -t public"
        environment:
            docker: "true"
        ports:
            - "6969:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
